services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=twitchu
      - POSTGRES_USER=twitchu
      - POSTGRES_PASSWORD=twitchu
  server:
    build:
      context: server
    ports:
      - 8000:8000
    volumes:
      - ./server:/server
    depends_on:
      - postgres
  nginx:
    build:
      context: nginx
    ports:
      - 80:80
    depends_on:
      - server
